### ISSUE TITLE
OpenCV linking problem causes build failed

### ISSUE THREAD

**Issue by tuandle** [wavelab/libwave#279] opened 2018-05-09 15:17 UTC
Hi,
I have an OpenCV linking problem when I tried to build the libwave library.
The error is as follows:
```In file included from /opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core.hpp:52:0,
                 from /opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videoio.hpp:46,
                 from /opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videoio/videoio.hpp:48,
                 from /home/libwave/wave_vision/include/wave/vision/utils.hpp:12,
                 from /home/libwave/wave_vision/src/utils.cpp:1:
/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cvdef.h:223:15: error: redefinition of ‘union Cv32suf’
 typedef union Cv32suf
```
As far as I understand this is because libwave can't link to OpenCV libraries. I tried to build against a local OpenCV-3.2.0 library but the error is the same.
I have no clue how to resolve this. Any help is greatly appreciated.

**Comment by leokoppel** [comment] 2018-08-02 15:26
Duplicate of https://github.com/wavelab/libwave/issues/267

> This issue is observed when opencv2 is installed in /usr/include/opencv2. One way to resolve it is to uninstall opencv2.

**Closed by leokoppel** 2018-08-02 15:26 UTC
